services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn monprojet.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nom-de-ta-bdd
          property: connectionString
